record xhr
rrweb-io/rrweb pull request #1105
Opened 2023-01-31 19:22 UTC by jlalmes

2023-02-02 13:15 UTC, jlalmes commented
Just a thought, the `NetworkRequest` payload is quite large because the `PerformanceEntry` interface contains more information than we likely need. What are your thoughts on changing it to the following? 
```ts
type NetworkRequest = {
  requestUrl: string;
  requestMethod: string;
  requestInitiator: InitiatorType | 'navigation';
  requestHeaders?: Headers;
  requestBody?: Body;
  responseStatus: number;
  responseTimeMs: number;
  responseHeaders?: Headers;
  responseBody?: Body;
};
```

2023-02-07 07:31 UTC, Mark-Fenng reviewed
This is a wonderful and exciting pull request, thank you very much. 
Most of code looks great. I'm also willing to add Chinese docs for it later.
It's better to have some test cases on the recorder side since this plugin is huge and importatnt.

2023-02-07 07:31 UTC, Mark-Fenng commented on packages/rrweb/src/plugins/network/record/index.ts
> +                const objBody = JSON.parse(xhr.response as string) as object;
It might not be safe to use the response as a string directly. The response can be other types, such as images, videos, etc. It's better to filter out these non-text responses as they can significantly increase the event size or leave the choice to the developers.

2023-02-07 07:31 UTC, Mark-Fenng commented on packages/rrweb/src/plugins/network/record/index.ts
> +        const reqBody = await res.clone().text();
Similarly, it's better to have a content type filter here.

2023-02-07 07:31 UTC, Mark-Fenng commented on packages/rrweb/src/plugins/network/record/index.ts
> +  responseBody?: string | null;
I'm wondering whether it is possible to have a property that represents the starting time of requests. 
Since only with duration, it's hard to determine when the request happens. Specially, with the option `recordInitialRequests` switched on, it's harder to determine when the requests happened.

2023-02-07 12:21 UTC, jlalmes commented on packages/rrweb/src/plugins/network/record/index.ts
> +  responseBody?: string | null;
agreed 👍
```diff
- responseDuration: number;
+ startTime: number;
+ endTime: number;
```

2023-02-07 17:47 UTC, jlalmes commented
Thanks for your review @Mark-Fenng - I have just updated this branch with all of the changes you have suggested! I plan to add some tests shortly.

Out of interest do you know when we plan to release `2.0.0-alpha.5`?

2023-02-07 17:52 UTC, jlalmes commented on packages/rrweb/src/plugins/network/record/index.ts
> +                const objBody = JSON.parse(xhr.response as string) as object;
Sounds good, `recordBody` now has the following signature.

```ts
recordBody?: boolean | string[] | { 
  request: boolean | string[]; 
  response: boolean | string[] 
};
```

- `true` records everything
- `false` records nothing
- `string[]` records only requests/response bodies with matching `Content-Type` headers.

Example:
```ts
getRecordNetworkPlugin({
  recordBody: ['application/json'],
  ...,
})
```

2023-02-08 05:20 UTC, Mark-Fenng commented on packages/rrweb/src/plugins/network/record/index.ts
> +                const objBody = JSON.parse(xhr.response as string) as object;
This thought is great but the structure of the option can be optimized IMO.
The current structure design is too complex for a single property `recordBody` and it's also hard to parse. For example, if I set `recordBody: ['application/json']`, the parsed `recordResponseBody` will always be true rather than a string array. You may have a try at it.
https://github.com/rrweb-io/rrweb/pull/1105/files#diff-7fb82041d48502b38e60b5d8e2901b6f9cb5ff213f8841e6f3b1f409c1a51ebaR229-R233
<img width="479" alt="image" src="https://user-images.githubusercontent.com/27533910/217441185-ac4455a1-8865-4019-92e3-55ec673c505f.png">


In my view, it's OK to have more optional properties rather than just one `recordBody`.

2023-02-08 05:23 UTC, Mark-Fenng commented on packages/rrweb/src/plugins/network/record/index.ts
> +  responseBody?: unknown;
We may use a more specific type definition here.

2023-02-08 05:36 UTC, Mark-Fenng commented
Thanks for applying all review suggestions. Although there are still a few small points that need to tweak, it's very close to the final version.

Here is a TODO list:

- [ ] improve the content type filter
- [ ] test cases
- [ ] Chinese docs (I will add them later)

I'm so sorry that, for the release of 2.0.0-alpha.5, I also don't have a specific date to tell. These days other team members are all busy with their work and some important pull requests for bug fixes are delayed.

2023-02-08 14:17 UTC, jlalmes commented on packages/rrweb/src/plugins/network/record/index.ts
> +                const objBody = JSON.parse(xhr.response as string) as object;
> `recordBody: ['application/json']`, the parsed `recordResponseBody` will always be `true`

> content type `"application/json; charset=UTF-8"` the current filter can't recognize

I have fixed the two bugs above, but have kept the signature of `recordBody` the same. I have added a function `shouldRecordBody` to simplify this complexity.

2023-02-09 05:29 UTC, YunFeng0817 submitted a review, later dismissed
With more tests, I think this pull request is good to go

2023-02-09 09:09 UTC, Juice10 commented
This looks great! I agree with @Mark-Fenng, if we have some more tests this will be ready to merge. Also I'm happy to spend some time working on the 2.0.0-alpha.5 release soon

2023-02-20 10:16 UTC, benjackwhite commented on docs/recipes/network.md
> +    rrweb.getRecordConsolePlugin({
Think this is a typo? 

```suggestion
    rrweb. getRecordNetworkPlugin({
```

2023-04-20 11:36 UTC, benjackwhite commented
@jlalmes need some help getting this across the finish line? This would be such a good improvement to the custom solution we have for network recording and things here look pretty solid, just needing some good tests it seems.

2023-05-09 03:43 UTC, yaoyuanrong commented
Is this plugin released?

2023-05-09 03:46 UTC, yaoyuanrong commented
I really need this feature。I think this is a very powerful feature

2023-10-19 00:15 UTC, antunesgabriel approved these changes

2023-10-19 18:26 UTC, benjackwhite requested changes
Saw this is starting to get reviewed and wanted to throw in a thought regarding `ignoreRequestFn` to see if we can't make it more flexible, as well as more inline with the text and input style approach.

2023-10-19 18:26 UTC, benjackwhite commented on packages/rrweb/src/plugins/network/record/index.ts
> +    );
It would be great if this was both filtering and cleansing.

The most typical case for privacy controls is:
"I want to filter out requests to this place"
"I wan't to ensure certain headers aren't included"
"I want to filter out PII from the response bodies".

This would all doable with a slight modification of the function:
```suggestion
    const requests = data.requests.reduce(
      (list, request) => {
        const maskedRequest = networkOptions.maskRequestFn(request)
        
        return maskedRequest ? [...list, maskedRequest] : list
      }, []
    );
```

Which then allows the function to be something like

```ts
maskRequestFn: (request: NetworkRequest): NetworkRequest | undefined  => {
  if (request.url.contains("rrweb-collector-api.com") {
    return
 }
 delete request.requestHeaders["Authorization"]
 request.responseBody = maskTextFn(request.responseBody)
 return request
}

```

2023-10-19 18:27 UTC, benjackwhite commented on packages/rrweb/src/plugins/network/record/index.ts
> +    );
In theory this could be added in a follow up PR as well. Happy to do that if that is the decision.

2023-11-04 10:20 UTC, pauldambra commented on packages/rrweb/src/plugins/network/record/index.ts
> +  const urlPerformanceEntries = win.performance.getEntriesByName(
If I'm understanding correctly I think we'd need to make this optional... 

If people already have their own code (or another dependency) tracking performance entries they might be calling https://developer.mozilla.org/en-US/docs/Web/API/Performance/clearResourceTimings already so we'd have a race. 

Since this usage comes after the response if someone is clearing the buffer as soon as they're able to then I guess that this code would lose the race.

I think it's cheap enough to have the observer running no matter what that you could have `recordRequestPerformance` and return early here so the signature becomes `Promise<PerformanceRequestTiming | null>`

2023-11-12 08:58 UTC, pauldambra commented on packages/rrweb/src/plugins/network/record/index.ts
> +  const urlPerformanceEntries = win.performance.getEntriesByName(
My mistake - 🤯 I've just read back through this and seen that the thrown error (and any other error here) are captured and swallowed where the returned promise is handled.

My preference would be to return null so that the flow is more clear but at least the error here doesn't bubble out

2023-11-17 19:33 UTC, pauldambra commented on packages/rrweb/src/plugins/network/record/index.ts
> +  }
Was playing with this...

If I understand correctly...

This entire block only exists so `isInitial: true` can be added to the callback payload. If we weren't adding that property then when creating the observer immediately below we could observe the entry types individually with `buffer: options.recordInitialRequests`

I can't think of the use-case for knowing a request was "initial" when playing back. (tbh I can't think why I'd not want to capture "initial" requests) But in the interests of starting with the smallest API because it's easier to add things. I'd be tempted to say we shouldn't record `initial` on the payload.

2023-11-22 16:18 UTC, pauldambra commented on packages/rrweb/src/plugins/network/record/index.ts
> +};
I was experimenting with this again...

We already capture Network timing and the `PerformanceEntry` spec uses `name` where this `NetworkRequest` timing uses `url`

It is more natural for the typing here to be something like

```
export type CapturedNetworkRequest = Omit<PerformanceEntry, 'toJSON'> & {
    method?: string
    initiatorType?: InitiatorType
    status?: number
    startTime?: number
    endTime?: number
    requestHeaders?: Headers
    requestBody?: Body
    responseHeaders?: Headers
    responseBody?: Body
    // was this captured before fetch/xhr could have been wrapped
    isInitial?: boolean
}
```

That way you can extend this to capture `PerformanceEntry`s and/or headers and/or body and only use one type

2024-01-01 21:17 UTC, pathik-appachhi commented
Hello,

I have recently started using rrrweb-io via the [cdn](https://cdn.jsdelivr.net/npm/rrweb@2.0.0-alpha.11/) . It would be very helpful to know when this plugin will be available on the CDN link.

2024-01-08 09:12 UTC, ShayMalchi commented
@jlalmes @YunFeng0817 Seems like this PR was approved long ago, can you please share what is the current blocker for merging? Many people in this thread are interested in it, and seems like most suggestions could be handled in followup PRs. Thank you!

2024-01-08 09:39 UTC, pauldambra commented
I'll just re-up this comment https://github.com/rrweb-io/rrweb/pull/1105#discussion_r1402360817

It's easier for me if we have `name` not `URL`. Since the performance observer uses `name` and emits more than just things with URLs.

2024-02-20 09:30 UTC, sharan-ravi commented
@jlalmes @pauldambra 
Thank you so much for this!

I was running into an issue with some of my requests not being recorded with this plugin, after digging deeper, turns out in case of certain requests, if the server doesn't return a [Timing-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin) response header, we wouldn't be able to track the performance metrics. Given this plugin throws an error when performance metrics are not available, these requests were not being recorded. 

While the performance metrics are not available, Other data on these requests are still available, so in my case I had to do something like this to still record these requests. 

```
getRequestPerformanceEntry(win, 'fetch', req.url, after, before)
                    .then((entry) => {
                        if (_isNull(entry)) {
                            const requests = prepareRequestWithoutPerformance(req, networkRequest)
                            cb({ requests })
                        } else {
                            const requests = prepareRequest(entry, req.method, res?.status, networkRequest)
                            cb({ requests })
                        } })

function prepareRequestWithoutPerformance(
    req: Request,
    networkRequest: Partial<CapturedNetworkRequest>,
): CapturedNetworkRequest[] {

    const reqJson = {
        url: req.url,
        method: req.method,
        requestHeaders: networkRequest.requestHeaders,
        requestBody: networkRequest.requestBody,
        responseHeaders: networkRequest.responseHeaders,
        responseBody: networkRequest.responseBody,
    }

    return [reqJson]
}
```

Is this expected?

2024-04-18 09:40 UTC, Juice10 commented
> My plan is to let it settle in our product for a week or two. And then I'll open a PR based on this one that would let us inject the things we'd varied - which might also be things other people would want to vary...
> 
> It won't be massively different - and of course the version that works for us might not be preferable generally
@pauldambra would you still be interested to open a PR based on the version you have running in production?

FYI: https://github.com/rrweb-io/rrweb/pull/1033 just got finished which moves the all of the plugins to the `packages/plugins/...` directory. Might be worth considering creating the PR based on that as well

2024-05-02 11:06 UTC, akhsri commented
Hi @jlalmes , When can we see this in rrweb package? it would be very powerful and helpful feature!

2024-05-09 10:07 UTC, pauldambra commented
@Juice10 definitely... our implementation has been pretty stable for a while now... it's just time that's stopping me 🙈 

I think the "tricky" thing will be separating our config/mapping needs out of the plugin but that's pretty mechanical non-ground-breaking stuff

2024-05-30 23:15 UTC, Marlonzao commented
Hello, is there a guide on how to download this plugin?

2024-05-31 00:12 UTC, Marlonzao commented
I have figuret it, you have to clone this repo https://github.com/jlalmes/rrweb/tree/feat/network-plugin then ckeckout to the branch "feat/network-plugin" and run "yarn && yarn run build:all" the files needed will be in the directory packages/rrweb/dist

2025-02-04 05:29 UTC, akshanshkmr commented
Hi,
Is there any plan to merge this?

2025-04-28 15:11 UTC, crutch12 commented
@pauldambra may we somehow merge it and publish new packages to npm? It would be really helpful 🙏

2025-04-28 19:17 UTC, crutch12 commented
I've updated the code and opened a new PR:
https://github.com/rrweb-io/rrweb/pull/1689

2025-04-28 19:43 UTC, crutch12 commented on packages/rrweb/src/plugins/network/record/index.ts
> +    );
Fixed here: https://github.com/rrweb-io/rrweb/pull/1689

2025-04-28 19:44 UTC, crutch12 commented on packages/rrweb/src/plugins/network/record/index.ts
> +  const urlPerformanceEntries = win.performance.getEntriesByName(
Fixed here: https://github.com/rrweb-io/rrweb/pull/1689

2025-04-28 19:44 UTC, crutch12 commented on packages/rrweb/src/plugins/network/record/index.ts
> +};
Fixed here: https://github.com/rrweb-io/rrweb/pull/1689

2026-06-05 16:42 UTC, closed without merging

2026-06-05 16:42 UTC, Juice10 commented
Thanks for contributing this @jlalmes! We just got it merged via https://github.com/rrweb-io/rrweb/pull/1689, thanks again for taking the time to do this and apologies that it took so long for us to merge it. Big thanks to everyone here that contributed as well!