Add Asset event type and capture assets
rrweb-io/rrweb pull request #1239
Opened 2023-06-08 14:37 UTC by Juice10

Asset events allow for asynchronous events containing (image or potentially other) assets.
See https://github.com/rrweb-io/rrweb/issues/860 for more info.

These are async events that get emmited after the original dom mutation events and can be used to inject these assets after the fact in the player or via post processing.

Todo:
- [ ] create asset event for assets that failed to load
- [ ] implement asset in player
- [ ] add flag to log assets being captured
- [ ] add documentation for recording config
- [ ] [docs] explain how its different to inline images
- [ ] decided whether or not to move the capturing and encoding to a web worker

2024-01-11 16:01 UTC, eoghanmurray reviewed
I'm wondering whether it's worth taking [this commit](fa2b165cc85678ceb016bd1a3db9be7da86cb534) out and merging in a separate PR?
Fine if not; maybe in future this sort of thing could be merged in earlier while rest of a PR is ongoing.

2024-01-16 15:40 UTC, Juice10 commented
> I'm wondering whether it's worth taking [this commit](https://github.com/rrweb-io/rrweb/pull/1239/commits/fa2b165cc85678ceb016bd1a3db9be7da86cb534) out and merging in a separate PR? Fine if not; maybe in future this sort of thing could be merged in earlier while rest of a PR is ongoing.

If we weren't on an alpha release that type of commit would also require us to do a major version change. Not sure if it makes sense now, it's bound to break some tests and those got fixed later in subsequent commits. But in general I do agree with you, this type of thing would be better in a separate PR

2024-02-04 04:19 UTC, Yuyz0112 commented on docs/recipes/assets.md
> +The `inlineImages` configuration option is deprecated and should not be used anymore. The previous implementation had some issues, namely rewriting events that are already emitted which might make yo
Forwarding to the new API is a good idea, but since it changes the behavior of the old config, shall we add breaking change notes to the changeset?

2024-02-04 04:20 UTC, Yuyz0112 commented on packages/rrdom-nodejs/package.json
> +    "rollup-plugin-typescript2": "^0.36.0",
this upgrade is great:)

2024-02-04 04:24 UTC, Yuyz0112 commented on packages/rrweb-snapshot/package.json
> +    "@rrweb/types": "^2.0.0-alpha.11"
we put types as dependencies instead of devDependencies because we import runtime enums?

2024-02-04 04:29 UTC, Yuyz0112 commented on packages/rrweb-snapshot/src/utils.ts
> +  ['IMG', new Set(['src', 'srcset'])],
It looks like the element types are not configurable in the captureAssets API.

I don't know if a user wants to capture the image src also wants to capture all video/audio elements.

But since the PR's scope is already big, we can leave this as a discussion and do it in the following PRs if needed.

2024-02-04 04:30 UTC, Yuyz0112 commented on packages/rrweb-snapshot/src/utils.ts
> +    const spaceIndex = trimmed.indexOf(' ');
shall we add some comments to inline two examples for the following if/else conditions

2024-02-04 04:32 UTC, Yuyz0112 commented on packages/rrweb-snapshot/tsconfig.json
> +      "path": "../types"
why we need this config?

2024-02-05 06:09 UTC, Yuyz0112 commented on packages/rrweb/src/replay/index.ts
> -    if (this.speedService.state.matches('normal')) {
why we are removing this?

2024-02-05 06:11 UTC, Yuyz0112 commented on packages/rrweb/src/replay/index.ts
> +  private async preloadAllAssets(timestamp: number): Promise<void[]> {
What will happen if users use the `addEvent` API to put more new asset events?

2024-02-05 06:15 UTC, Yuyz0112 commented on packages/rrweb/src/replay/asset-manager/index.ts
> +  public reset(config?: captureAssetsParam | undefined): void {
Why do we have to reset when a meta event is captured?

2024-02-05 16:16 UTC, Juice10 commented on docs/recipes/assets.md
> +The `inlineImages` configuration option is deprecated and should not be used anymore. The previous implementation had some issues, namely rewriting events that are already emitted which might make yo
Good idea! Here is the changeset for it: https://github.com/rrweb-io/rrweb/pull/1239/commits/0115cb65895e0bceb38b4bf36273b7d221a0d4b0

2024-02-05 16:27 UTC, Juice10 commented on packages/rrweb-snapshot/src/utils.ts
> +  ['IMG', new Set(['src', 'srcset'])],
Yes that would be a nice configuration option I think (which I would indeed prefer to do separately from this PR). And I think adding a max-asset size would also be a useful configuration option as well.

2024-02-05 16:41 UTC, Juice10 commented on packages/rrweb-snapshot/src/utils.ts
> +    const spaceIndex = trimmed.indexOf(' ');
Good idea, I've added that here: https://github.com/rrweb-io/rrweb/pull/1239/commits/4484a259a00120c690d7e890903b7f865429d2f2

2024-02-06 11:09 UTC, Juice10 commented on packages/rrweb/src/replay/asset-manager/index.ts
> +  public reset(config?: captureAssetsParam | undefined): void {
This is for live-mode/addEvent. Once a meta event is triggered its an indication that a page navigation has happened. That tells us that we don't have to keep waiting for new asset events to show up, hence the `reset` being called.

2024-02-06 11:27 UTC, Juice10 commented on packages/rrweb/src/replay/index.ts
> +  private async preloadAllAssets(timestamp: number): Promise<void[]> {
If live mode is triggered we have a slightly different way of working.
In that case we wait for the asset to be loaded before we add its `src` attribute with the final url
https://github.com/rrweb-io/rrweb/blob/a6a1c9307b33d20a4bf928db52aba59ec09ca6a5/packages/rrweb/src/replay/asset-manager/index.ts#L192-L221

2024-02-06 16:51 UTC, Juice10 commented on packages/rrweb-snapshot/package.json
> +    "@rrweb/types": "^2.0.0-alpha.11"
I think this is why I did it, but to be honest I don't remember so I'll move it to `devDependencies` and see if that breaks anything, maybe it will be fine.

2024-02-08 15:08 UTC, Juice10 commented on packages/rrweb-snapshot/package.json
> +    "@rrweb/types": "^2.0.0-alpha.11"
Just moved this to `devDependencies` and it seems to work fine. So we can leave it that way AFAIK

2024-02-11 06:25 UTC, Yuyz0112 commented on packages/rrweb/src/replay/asset-manager/index.ts
> +  public reset(config?: captureAssetsParam | undefined): void {
I see. But do we need to store the capture config in the meta event, and reload it as `this.config = config` when a meta event is emitted?

Or we can think the capture config is the same across a session and also call reset when a meta event is emitted, but without storing a copy of the capture params in the meta event?

2024-02-11 06:28 UTC, Yuyz0112 commented on packages/rrweb/src/record/observers/asset-manager.ts
> +            this.capturingURLs.delete(url);
how about move this line and the same line in the error block into a `finally` block?

2024-02-11 06:32 UTC, Yuyz0112 commented
Just reviewed the last two files: the asset manager observer and the replay side manager, really cool implementation!

Leave some small comments, and we should be able to merge this in the following days.

2024-03-15 16:37 UTC, eoghanmurray commented
Not sure if this is a goal or a non-goal, but should we be collecting all assets for the `srcset` attribute? Shouldn't we be able to tell which one of the images is the one that will need to be rendered?

2024-03-20 12:07 UTC, eoghanmurray requested changes
Rename cacheable -> capturable

2024-03-20 12:07 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/utils.ts
> +export const CACHEABLE_ELEMENT_ATTRIBUTE_COMBINATIONS = new Map([
```suggestion
export const CAPTURABLE_ELEMENT_ATTRIBUTE_COMBINATIONS = new Map([
```

2024-03-20 12:07 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/utils.ts
> +  const acceptedAttributesSet = CACHEABLE_ELEMENT_ATTRIBUTE_COMBINATIONS.get(
```suggestion
  const acceptedAttributesSet = CACHEABLE_ELEMENT_ATTRIBUTE_COMBINATIONS.get(
```

2024-03-20 13:17 UTC, eoghanmurray requested changes
more cacheable -> capturable

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/snapshot.ts
> +  isAttributeCacheable,
```suggestion
  isAttributeCapturable,
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/snapshot.ts
> +      if (value && onAssetDetected && isAttributeCacheable(n, attr.name)) {
```suggestion
      if (value && onAssetDetected && isAttributeCapturable(n, attr.name)) {
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/utils.ts
> +export function isAttributeCacheable(n: Element, attribute: string): boolean {
```suggestion
export function isAttributeCapturable(n: Element, attribute: string): boolean {
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/test/utils.test.ts
> +import { isAttributeCacheable, isNodeMetaEqual } from '../src/utils';
```suggestion
import { isAttributeCapturable, isNodeMetaEqual } from '../src/utils';
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/test/utils.test.ts
> +  describe('isAttributeCacheable()', () => {
```suggestion
  describe('isAttributeCapturable()', () => {
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/test/utils.test.ts
> +          expect(isAttributeCacheable(element, attribute)).toBe(true);
```suggestion
          expect(isAttributeCapturable(element, attribute)).toBe(true);
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb-snapshot/test/utils.test.ts
> +          expect(isAttributeCacheable(element, attribute)).toBe(false);
```suggestion
          expect(isAttributeCapturable(element, attribute)).toBe(false);
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/record/mutation.ts
> +            this.assetManager.isAttributeCacheable(target, attributeName)
```suggestion
            this.assetManager.isAttributeCapturable(target, attributeName)
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/record/observers/asset-manager.ts
> +import { isAttributeCacheable } from 'rrweb-snapshot';
```suggestion
import { isAttributeCapturable } from 'rrweb-snapshot';
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/record/observers/asset-manager.ts
> +  public isAttributeCacheable(n: Element, attribute: string): boolean {
```suggestion
  public isAttributeCapturable(n: Element, attribute: string): boolean {
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/record/observers/asset-manager.ts
> +    return isAttributeCacheable(n, attribute);
```suggestion
    return isAttributeCapturable(n, attribute);
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/replay/asset-manager/index.ts
> +import { getSourcesFromSrcset, isAttributeCacheable } from 'rrweb-snapshot';
```suggestion
import { getSourcesFromSrcset, isAttributeCapturable } from 'rrweb-snapshot';
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/replay/asset-manager/index.ts
> +    if (!isAttributeCacheable(n as Element, attribute)) return false;
```suggestion
    if (!isAttributeCapturable(n as Element, attribute)) return false;
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/replay/asset-manager/index.ts
> +    if (!originalValue || !this.isCacheable(node, attribute, originalValue))
```suggestion
    if (!originalValue || !this.isCapturable(node, attribute, originalValue))
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/types/src/index.ts
> +  abstract isCacheable(n: Element, attribute: string, value: string): boolean;
```suggestion
  abstract isCapturable(n: Element, attribute: string, value: string): boolean;
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrdom/src/diff.ts
> +    if (assetManager?.isCacheable(oldTree, name, newValue)) {
```suggestion
    if (assetManager?.isCapturable(oldTree, name, newValue)) {
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrdom/test/diff.test.ts
> +          isCacheable: jest.fn(),
```suggestion
          isCapturable: jest.fn(),
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrdom/test/diff.test.ts
> +        (assetManager.isCacheable as jest.Mock)
```suggestion
        (assetManager.isCapturable as jest.Mock)
```

2024-03-20 13:17 UTC, eoghanmurray commented on packages/rrweb/src/replay/asset-manager/index.ts
> +  public isCacheable(
```suggestion
  public isCapturable(
```

2024-03-20 13:55 UTC, eoghanmurray commented on packages/rrweb/src/replay/asset-manager/index.ts
> +          node.setAttribute('src', '//:0');
```suggestion
          // special value to prevent a broken image icon while asset is being loaded
          node.setAttribute('src', '//:0');
```

2024-06-21 11:31 UTC, eoghanmurray commented on package.json
> +    "check-types": "yarn run concurrently --success=all -r -m=1 'yarn workspaces-to-typescript-project-references --check' 'yarn turbo run check-types --continue'",
Is this a regression from the `vite` way to the old way?
this longer version looks to have been added Nov 27 in f986245deb17854f6c499b4ee7baf1d4c0f12baf

2024-06-25 12:26 UTC, Juice10 commented on package.json
> +    "check-types": "yarn run concurrently --success=all -r -m=1 'yarn workspaces-to-typescript-project-references --check' 'yarn turbo run check-types --continue'",
Just rebased, should be fixed now

2026-09-04 08:56 UTC, Juice10 commented
Superseeded by https://github.com/rrweb-io/rrweb/pull/1239

2026-09-04 08:56 UTC, closed without merging