optimize isParentRemoved for large remove lists
rrweb-io/rrweb pull request #1368
Opened 2023-12-06 17:07 UTC by mdellanoce

Encountered a mutations that removes ~1400 nodes. Noticed a lot of the processing time was tied up in `isParentRemoved`, which repeatedly does an iterative search of the `removes` array. I added a map (nodeId => index in removes array) to speed up this process. See before/after images below:

Before:
<img width="547" alt="image" src="https://github.com/rrweb-io/rrweb/assets/541814/320e916f-0310-4bed-a8df-12ba6b641544">

After:
<img width="556" alt="image" src="https://github.com/rrweb-io/rrweb/assets/541814/aa13cea1-a655-4ee4-b041-64eecf430ceb">

I didn't see a difference in the existing benchmarks, even though one of them involves removing a lot of nodes. The problem functionality shown in the profiles above involved scrolling through a large table that would dynamically remove/add pages of data as you scroll.

2024-04-13 22:45 UTC, eoghanmurray requested changes

2024-04-13 22:45 UTC, eoghanmurray commented on packages/rrweb/src/record/mutation.ts
> +            this.removesMap.set(nodeId, this.removes.length - 1);
If that's true, then rather than adding another variable that needs to be maintained, we could convert the `this.removes` type into a Map indexed by nodeId `new Map<number, removedNodeMutation>();`
and then when the payload is emitted, convert to the expected array:

`-removes: this.removes`
`+removes: Array.from(this.removes.values())`

2024-05-01 19:07 UTC, colingm commented on packages/rrweb/src/record/mutation.ts
> +            this.removesMap.set(nodeId, this.removes.length - 1);
yeah the map was unnecessary before, changed `removes` to just be a map of the id to the mutation as you suggested

2025-02-11 21:23 UTC, closed without merging

2025-02-11 21:23 UTC, eoghanmurray commented
I think this has been superseded by #1543 which no longer does the expensive `removes.some((r) => r.id === parentId)`