Capture stylesheets designated as `rel="preload"`
rrweb-io/rrweb pull request #1374
Opened 2023-12-12 03:42 UTC by andrewpomeroy

Encountered an issue where stylesheets failed to capture when they were referenced by link tag with `rel="preload"` instead of `rel="stylesheet"`. This change will broadens the rules so that these preloaded stylesheets can also be recognized and captured at the snapshot phase.

For background: This attribute assignment is a performance hack, meant to allow the stylesheet to be preloaded, and is usually combined with `onload="this.rel = 'stylesheet'"` so that it is still recognized as a stylesheet at runtime. The snapshot phase, naturally, will miss this unless we provide guidance. More info: https://stackoverflow.com/a/61889123

In addition, I added reinforced pattern matching for both `.css` file paths—for the aforementioned scenario and the existing `.js` / `rel="prefetch"` scenario—so that paths will still be matched if they include search parameters or fragments.

2023-12-15 13:11 UTC, Juice10 requested changes
Thanks for creating this PR @andrewpomeroy! This is a nice addition to rrweb. I found two minor things, check them out and let me know what you think and then we can merge this.

2023-12-15 13:11 UTC, Juice10 commented on packages/rrweb-snapshot/src/utils.ts
> +  const url = new URL(path, baseURL ?? window.location.href);
We should wrap this in a try catch in case someone adds a gibberish pathname that doesn't get recognised by URL and will otherwise throw

2023-12-15 13:11 UTC, Juice10 commented on packages/rrweb-snapshot/src/utils.ts
> +  const match = url.pathname.match(regex);
I'm not sure you need to match against `?` or `#`, according to the MDN documentation .pathname already cuts this off

2023-12-15 20:03 UTC, andrewpomeroy commented on packages/rrweb-snapshot/src/utils.ts
> +  const match = url.pathname.match(regex);
Dropped it 👍

2023-12-15 20:03 UTC, andrewpomeroy commented on packages/rrweb-snapshot/src/utils.ts
> +  const url = new URL(path, baseURL ?? window.location.href);
Done! 👌

2023-12-15 20:07 UTC, andrewpomeroy commented
Thanks @Juice10! Your suggestions make perfect sense. I went ahead and made those changes.

2023-12-20 20:42 UTC, andrewpomeroy commented
Hi @Juice10 ! It looks like this is now failing tests, which look to be the same tests currently failing on master. I tried checking out https://github.com/rrweb-io/rrweb/pull/1366 and fixing them myself, but didn't get much traction.

My team is looking to close out this issue on our end; no pressure at all intended, but what are the chances of this getting merged/released in the next few weeks? We just need to be able to make the call whether to fork or not. Thanks again for your contributions 🙂

2023-12-20 20:53 UTC, andrewpomeroy commented
@Juice10 Whoops, just saw your comment here https://rrweb.slack.com/archives/C01BYDC5C93/p1702300072935979?thread_ts=1701887171.474259&cid=C01BYDC5C93 ! I'm assuming it won't be much longer then 😄 Looking forward to it!

2023-12-21 06:57 UTC, Juice10 commented
@andrewpomeroy hang tight Andrew, unfortunately I wasn’t able to fix master in https://github.com/rrweb-io/rrweb/pull/1366 (I should close that one), but indeed as mentioned in slack I’m hoping to merge https://github.com/rrweb-io/rrweb/pull/1239 soon which does fix master, and then we can merge this PR and do a release.

2023-12-21 08:12 UTC, andrewpomeroy commented
Great to hear! Thanks for the update.

2024-02-02 11:07 UTC, Juice10 commented
@andrewpomeroy hey Andrew, could you pull from master, ci is passing now

2024-02-12 17:19 UTC, Juice10 approved these changes

2024-02-12 17:19 UTC, merged

2024-05-04 00:04 UTC, eoghanmurray commented
> and is usually combined with onload="this.rel = 'stylesheet'" so that it is still, upon load, recognized as a stylesheet at runtime

Shouldn't this get picked up as a mutation?  And I think the mutation should then serialize the stylesheet correctly?
I think we need a test for this scenario to either demonstrate the `preload` bit or remove it if it isn't necessary.

2024-05-22 06:25 UTC, andrewpomeroy commented
> Shouldn't this get picked up as a mutation?
It's been a while since I've looked at this, but to the best of my memory— these mutations don't trigger a full snapshot, which is when the stylesheet-inlining process would take place.

2024-05-22 11:50 UTC, eoghanmurray commented
Yes, thanks — I actually have since written some tests and done some more work on this; the problem was that the mutation weren't doing anything when an attribute change caused a <link> to 'become a stylesheet'
More details here: 
https://github.com/rrweb-io/rrweb/pull/1483
which is still draft and WIP

2024-05-27 06:07 UTC, andrewpomeroy commented
Gotcha. Good thinking! I'm all for it.