Fix some css issues with :hover and rewrite max-device-width
rrweb-io/rrweb pull request #1431
Opened 2024-03-21 11:26 UTC by eoghanmurray

- Fix: We weren't recursing into media queries (or @supports etc.) to rewrite `:hover` pseudoclasses
 - Extension for replay: replace `min-device-width` and similar with `min-width` as the former looks out at the browser viewport whereas we need it to look at the replayer iframe viewport
 - Fix a gap in the css replayer caching if neither of the above were present in the css file

2024-03-21 13:14 UTC, Juice10 requested changes
Good catch @eoghanmurray! Found a little typing improvement for you, but apart from that this is looking ready for release!

2024-03-21 13:14 UTC, Juice10 commented on packages/rrweb-snapshot/src/rebuild.ts
> +  function getSelectors(rule: any) {
There is some types you could use from `./css.ts` to type this.
```suggestion
  function getSelectors(rule: StyleRules) {
```

2024-03-21 13:14 UTC, Juice10 commented on packages/rrweb-snapshot/src/rebuild.ts
> +  function getSelectors(rule: any) {
You might need to change the name of `rule` here though --^

2024-03-21 13:14 UTC, Juice10 commented on packages/rrweb-snapshot/test/rebuild.test.ts
> +}`,
I think you can add whitespace here to make the tests a little less messy, unless I'm missing something it should be fine.
```suggestion
         ul li.multiline
         b:hover
         img,
         ul li.specified c:hover img {
           color: white
         }`;
      expect(adaptCssForReplay(cssText, cache)).toEqual(
        `ul li.specified a:hover img, ul li.specified a.\\:hover img,
         ul li.multiline
         b:hover
         img, ul li.multiline
         b.\\:hover
         img,
         ul li.specified c:hover img, ul li.specified c.\\:hover img {
           color: white
         }`,
```

2024-03-21 17:05 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/rebuild.ts
> +  function getSelectors(rule: any) {
This is actually using css.ts which has it's own interface.
I wasted a half hour trying to figure out the typings.  I can't see the benefit of typings, it has to iterate over note only StyleRules types but implementations of Node interface (see css.ts)

I get the following error if I add `Node` there:

```
src/rebuild.ts:85:30 - error TS2339: Property 'forEach' does not exist on type '{}'.

85       (rule.selectors || []).forEach((selector: string) => {
```

2024-03-22 14:55 UTC, Juice10 commented on packages/rrweb-snapshot/src/rebuild.ts
> +  function getSelectors(rule: any) {
Maybe I can hop on a call with you, we can try and figure it out together?

2024-03-25 14:44 UTC, Juice10 approved these changes

2024-03-26 15:44 UTC, merged