Asset event attrs in dom
rrweb-io/rrweb pull request #1433
Opened 2024-03-25 17:47 UTC by eoghanmurray

This is for evaluation by Justin

2024-03-26 14:20 UTC, Juice10 commented on packages/rrweb/test/__snapshots__/integration.test.ts.snap
> +              \\"rr_captured_src\\": \\"blob:http://localhost:3030/d3df2ac2-68fe-471f-b5a7-00a51544a69c\\"
I'm not sure why, but its seems like the specifics haven't been replaced by `:xxxx/...` this will generate a unique url every time the tests runs which will cause this to fail if that hasn't been removed by `stringifySnapshots`

2024-03-26 14:24 UTC, Juice10 commented on packages/rrweb/test/record/__snapshots__/cross-origin-iframes.test.ts.snap
> +                      \\"rr_captured_src\\": \\"http://localhost:3030/html/audio.html\\"
Looks like `rr_src` isn't being kept intact here. From: https://github.com/rrweb-io/rrweb/blob/43d901105e9c6138b07389bf36bdffc24ef491e4/packages/rrweb/src/record/mutation.ts#L583-L596

2024-03-26 14:24 UTC, Juice10 commented on packages/rrweb/test/record/__snapshots__/cross-origin-iframes.test.ts.snap
> +                      \\"rr_captured_src\\": \\"http://localhost:3030/html/blank.html\\"
Same as https://github.com/rrweb-io/rrweb/pull/1433/files/842fc54800d3b64f2683232987e6811716a47d93..8b66efe44705c70ef8a7e77620e09946c8673cc4#r1539355070

2024-03-26 14:24 UTC, Juice10 commented on packages/rrweb/test/record/__snapshots__/cross-origin-iframes.test.ts.snap
> +                      \\"rr_captured_src\\": \\"http://localhost:3030/html/blank.html\\"
Same as https://github.com/rrweb-io/rrweb/pull/1433/files/842fc54800d3b64f2683232987e6811716a47d93..8b66efe44705c70ef8a7e77620e09946c8673cc4#r1539355070

2024-04-02 13:20 UTC, eoghanmurray commented on packages/rrweb/test/__snapshots__/integration.test.ts.snap
> +              \\"rr_captured_src\\": \\"blob:http://localhost:3030/d3df2ac2-68fe-471f-b5a7-00a51544a69c\\"
thanks, I fixed this up in packages/rrweb/test/utils.ts

2024-04-04 10:04 UTC, Juice10 requested changes
Really loving this @eoghanmurray! I fixed your typing issues for you

2024-04-05 09:16 UTC, Juice10 commented on packages/rrweb/src/replay/canvas/2d.ts
> +  const args = (await Promise.all(mutationArgsPromises)) as unknown[];
```suggestion
  const args = await Promise.all<unknown>(mutationArgsPromises);
```

2024-06-11 09:41 UTC, eoghanmurray commented
This is incorporated into #1475 and doesn't need any further evaluation as we're going to take this approach

2024-06-11 09:41 UTC, closed without merging