Added support for deprecated addRule & removeRule methods
rrweb-io/rrweb pull request #1515
Opened 2024-06-18 15:50 UTC by okejminja

We recently had a client on our fork who still uses addRule & removeRule (bad practice, I know, but we had to support 'em)

This PR add support for deprecated methods [addRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule) & [removeRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/removeRule)

Instead of writing duplicate code to support these or make some sort of an abstraction I just "transpiled" the props from addRule to what insertRule accepts and called the original insertRule or deleteRule accordingly – let you guys' methods handle the rest

Also expanded the test for capturing stylesheets to test this

LMK what you think

2024-06-19 08:35 UTC, Juice10 requested changes

2024-06-19 08:35 UTC, Juice10 commented on packages/rrweb/test/__snapshots__/record.test.ts.snap
> -exports[`record > captures stylesheet rules 1`] = `
Looks like you removed this snapshot instead of committing the updated code with the changes you added to the `captures stylesheet rules` test.

2024-06-19 09:00 UTC, okejminja commented on packages/rrweb/test/__snapshots__/record.test.ts.snap
> -exports[`record > captures stylesheet rules 1`] = `
Must've missed staging the file

2024-06-21 17:19 UTC, eoghanmurray requested changes

2024-06-21 17:19 UTC, eoghanmurray commented on packages/rrweb/src/record/observer.ts
> +    index?: number,
If `index` is undefined, the default will be zero (the `insertRule` default)
However `addRule` default is cssRules.length https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule#index
Could we supply this new default before passing it off to insertRule?

2024-06-21 20:51 UTC, okejminja commented on packages/rrweb/src/record/observer.ts
> +    index?: number,
Good catch! 
When supplying cssRules.length

```javascript
  win.CSSStyleSheet.prototype.addRule = function (
    this: CSSStyleSheet,
    selector: string,
    styleBlock: string,
    index: number = this.cssRules.length,
  ) {
    const rule = `${selector} { ${styleBlock} }`;
    return win.CSSStyleSheet.prototype.insertRule.apply(this, [rule, index]);
  };
```

I am getting an error when running the test, specifically when deleting rules
`DOMException: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (3) is larger than the maximum index (2).`

Will investigate and update

2024-06-21 21:23 UTC, okejminja commented on packages/rrweb/src/record/observer.ts
> +    index?: number,
I ended up separating the tests since idx kept moving around when calling deleteRule and removeRule in sequence

2024-07-18 08:18 UTC, eoghanmurray approved these changes

2024-07-23 09:10 UTC, Juice10 approved these changes

2024-07-23 09:10 UTC, merged