fix: don't bundle everything into console recorder
rrweb-io/rrweb pull request #1594
Opened 2024-11-02 23:16 UTC by pauldambra

| before | after |
|<img width="1377" alt="Screenshot 2024-11-02 at 23 31 05" src="https://github.com/user-attachments/assets/02713b4d-ff46-4211-9d10-f4f175ab408a">|<img width="1375" alt="Screenshot 2024-11-03 at 00 13 35" src="https://github.com/user-attachments/assets/08b0a0ec-2b13-44e3-b0fe-397392527a0e">|

the use of `utils.patch` from `rrweb` in the `console` plugin was including the whole of rrweb in the console recorder.

move the patch function into the existing `@rrweb/utils` package fixes this

(I've only proven the bundle is fixed - i'm hoping CI proves the recorder still works 😅 )

2024-11-02 23:37 UTC, pauldambra commented on package.json
> +    "rollup-plugin-visualizer": "^5.12.0",
i've lost track of the number of times these bundle visualisers have come in useful for me

2024-11-02 23:37 UTC, pauldambra commented on packages/plugins/rrweb-plugin-console-record/src/index.ts
> -import { utils } from 'rrweb';
this is the fix here... this line was including the whole of rrweb

2024-12-06 16:37 UTC, Juice10 requested changes
This looks really good @pauldambra, I had a couple tweaks, mainly due to the release of rrweb 2.0.0-alpha.18
But as soon as they are tackled we can merge this one and do another release.
FYI: You might have to pull in master to fix the tests, after adding the suggestions.

2024-12-06 16:37 UTC, Juice10 commented on .changeset/nasty-guests-dream.md
> +move patch function into rrweb/utils to improve bundling
```suggestion
Move patch function into @rrweb/utils to improve bundling
```

2024-12-06 16:37 UTC, Juice10 commented on .github/workflows/ci-cd.yml
> +          pattern: "**/dist/*.js"
Adds support for all filetypes used in bundling
```suggestion
          pattern: "**/dist/*.{js,cjs,mjs,css}"
```

2024-12-06 16:37 UTC, Juice10 commented on packages/plugins/rrweb-plugin-console-record/package.json
> +    "@rrweb/utils": "^2.0.0-alpha.17"
Release was just done so we need to reference .18
```suggestion
    "rrweb": "^2.0.0-alpha.18",
    "@rrweb/utils": "^2.0.0-alpha.18"
```

2024-12-06 16:37 UTC, Juice10 commented on packages/record/package.json
> +    "@rrweb/utils": "^2.0.0-alpha.17"
```suggestion
    "rrweb": "^2.0.0-alpha.18",
    "@rrweb/utils": "^2.0.0-alpha.18"
```

2024-12-10 11:59 UTC, Juice10 approved these changes

2025-01-17 10:23 UTC, pauldambra commented
yuck, I tried to be clever and as always that backfired... i'll recreate this PR from a person fork 🫠

2025-01-17 10:23 UTC, closed without merging