fix(snapshot): Change to ignore all `link[rel="modulepreload"]` (#228)
rrweb-io/rrweb pull request #1614
Opened 2024-12-17 22:04 UTC by billyvg

... removes requirement to have `as="script"` attribute as it is optional (also `modulepreload` implies script).

Also fixes `prefetch` to extract file extension instead of checking end of string since there can be URL parameters.

2024-12-17 22:05 UTC, billyvg commented on packages/rrweb-snapshot/src/rebuild.ts
> +            extractFileExtension(n.attributes.href) === 'js'
This is what is done in [`snapshot.ts`](https://github.com/getsentry/rrweb/blob/fix-snapshot-link-modulepreload-ignore-all-up/packages/rrweb-snapshot/src/snapshot.ts#L828)

2025-02-04 14:29 UTC, eoghanmurray requested changes

2025-02-04 14:29 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/snapshot.ts
>            (sn.attributes.rel === 'preload' ||
```suggestion
          ((sn.attributes.rel === 'preload' && sn.attributes.as === 'script') ||
```
The rel="preload" and as="script" originally went together before https://github.com/rrweb-io/rrweb/pull/1128/files

2025-02-04 17:59 UTC, billyvg commented on packages/rrweb-snapshot/src/snapshot.ts
>            (sn.attributes.rel === 'preload' ||
For `preload`, should we check: `as="script"` OR file extension == "js"? 

(Users don't always write HTML according to spec)

2025-02-06 12:24 UTC, eoghanmurray commented on packages/rrweb-snapshot/src/snapshot.ts
>            (sn.attributes.rel === 'preload' ||
I believe that the `as` part is necessary for the preload to 'work' correctly:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#as
So I'd be happy to conform to that.  
Otherwise we could add it to the following clause as in 

```
-        sn.attributes.rel === 'prefetch' &&
+        `['prefetch', 'preload'].includes(sn.attributes.rel) &&
```

but personally I'm not convinced that's necessary

2025-02-14 23:22 UTC, eoghanmurray approved these changes

2025-02-14 23:28 UTC, eoghanmurray commented on .changeset/short-hounds-confess.md
> +Change to ignore all link[rel="modulepreload"] instead of including only those with `as="script"`
```suggestion
Change to ignore all link[rel="modulepreload"] instead of including only those with `as="script"`
Properly check file extension on prefetch <link> elements to correctly ignore url params
```

2025-02-14 23:31 UTC, merged