Fix CSSStyleSheet applying when node doesn't exist in DOM
rrweb-io/rrweb pull request #529
Opened 2021-04-02 22:22 UTC by VladimirMilenko

Currently, during the node replacement, the `sheet` property is being automatically assigned to null. 
The check doesn't seem to have any effect on the insertion functionality, rather than the DOM nodes order. The style DOM node will be the first one in the HEAD tag.

I've also added a test which is able to check, whether the stylesheet rule exists in the sheet after insertion.

Fixes https://github.com/rrweb-io/rrweb/issues/525

2021-04-02 22:23 UTC, VladimirMilenko commented
cc @Juice10
This change is removing the check you added. Could you provide some info, whether that might create an issue?

2021-04-08 10:52 UTC, Yuyz0112 commented
LGTM

@Mark-Fenng PTAL

2021-04-08 11:48 UTC, Mark-Fenng commented
A great way to fix the issue.
BTW, is placeholderNode still necessary to exist?

2021-04-08 12:07 UTC, Juice10 requested changes
Really loving this, great work @VladimirMilenko

2021-04-08 12:07 UTC, Juice10 commented on test/replayer.test.ts
> +        rules.some(x=>x.selectorText === ".css-1fbxx79")
Would be nice if we could simplify this a little
```suggestion
      const rules = [...replayer.iframe.contentDocument.styleSheets].map((sheet)=> sheet.rules);
      rules.some(x=>x.selectorText === ".css-1fbxx79")
```

2021-04-08 12:07 UTC, Juice10 commented on test/replayer.test.ts
> +        rules.some(x=>x.selectorText === ".css-1fbxx79")
Same goes for here
```suggestion
      const rules = [...replayer.iframe.contentDocument.styleSheets].map((sheet)=> sheet.rules);
      rules.some(x=>x.selectorText === ".css-1fbxx79")
```

2021-04-08 12:38 UTC, Juice10 commented
> A great way to fix the issue.
> BTW, is placeholderNode still necessary to exist?

As far as I can remember it is necessary the first time the `.sheet` is accessed.
But for performance reasons it would be advisable skip the placeholder/adding-stylesheet-to-dom part when the node already exists in the `virtualStyleRulesMap`.

2021-07-03 05:39 UTC, Juice10 commented
It looks like constructible stylesheets (`new CSSStyleSheet`) is still in the [proposal phase](https://wicg.github.io/construct-stylesheets/) and is only implemented in Chrome, and [Firefox (behind experimental flag)](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#constructable_stylesheets).
In Safari I couldn't get it working directly but I was able to access it via a workaround: `Object.create(CSSStyleSheet.prototype)`

We might be able to get it working by using this polyfill: https://github.com/calebdwilliams/construct-style-sheets

2021-07-08 20:11 UTC, Juice10 commented
@VladimirMilenko feel free to close this PR. I ended up incorporating most of it in https://github.com/rrweb-io/rrweb/pull/618 which fixes this issue.

2021-07-09 07:22 UTC, closed without merging