implement video seek feature
rrweb-io/rrweb pull request #593
Opened 2021-06-23 09:32 UTC by bachmanity1

Listening for `seeked` event helps to synchronize media content between recorded and replayed page.

2021-06-23 10:48 UTC, Yuyz0112 requested changes

2021-06-23 10:48 UTC, Yuyz0112 commented on src/types.ts
> +  attributes: {
remove the `attributes` namespace looks similar to other param structure

2021-06-23 10:48 UTC, Yuyz0112 commented on src/types.ts
> +  attributes: {
BTW, since we do not have `currentTime` property before this patch, we should mark this property as optional `currentTime?: number`, so the replayer knows it will handle legacy events without this property.

2021-06-24 01:25 UTC, bachmanity1 commented
@Yuyz0112 I reflected your comments.

2021-06-24 02:44 UTC, Yuyz0112 commented on src/replay/index.ts
> +            mediaEl.currentTime = d.currentTime as number;
maybe this?

```ts
if (d. currentTIme) {
  mediaEl.currentTime = d.currentTime
}
```

2021-06-24 04:09 UTC, bachmanity1 commented on src/replay/index.ts
> +            mediaEl.currentTime = d.currentTime as number;
changed the code.

2021-06-24 05:40 UTC, Yuyz0112 requested changes

2021-06-24 05:40 UTC, Yuyz0112 commented on src/record/observer.ts
> +    const { target } = event;
@bachmanity1 Sorry I missed this line in the previous review.

`getEventTarget` is a util to get event target from normal DOM scope and shadow DOM, so I think it's needed here.

2021-06-24 05:53 UTC, bachmanity1 commented on src/record/observer.ts
> +    const { target } = event;
fixed.

2021-06-24 10:27 UTC, Yuyz0112 commented
@bachmanity1 Thanks!

2021-06-24 10:28 UTC, Yuyz0112 approved these changes

2021-06-24 10:28 UTC, merged