Merge rrweb, rrweb-snapshot, rrweb-player into a mono repository
rrweb-io/rrweb pull request #595
Opened 2021-06-25 11:16 UTC by Mark-Fenng

1. In this PR, I use [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) to link multiple packages.
2. Update Travis-CI config.

Related issue #582

2021-06-26 08:09 UTC, Yuyz0112 commented
Short questions before looking into the PR:

1. Is this only works when developers using yarn instead of npm?
2. Is it possible to keep the git history of snapshot and player repo after moving these files.

2021-06-26 08:24 UTC, Mark-Fenng commented
1. I think if developers want to link three repos, yarn or npm(version>=7) is required.
2. I did a little research about merge of git history and it seems like sub-tree merge is good approach.

2021-06-26 08:42 UTC, Yuyz0112 commented
Not quite sure how does lerna does the link things.

2021-06-26 08:49 UTC, Mark-Fenng commented
In the doc of yarn workspaces, it says yarn workspaces provide the basic support for linking packages and lerna has much more abilities. 
According to the discussion in the issue, I suppose workspaces can meet our requirement for now.

2021-06-27 19:30 UTC, Juice10 commented
You might also want to consider [pnpm](https://pnpm.io) instead of Lerna, I don't have a lot of experience with it but it seems like it would simplify things: https://www.takeshape.io/articles/why-we-switched-from-yarn-to-pnpm/

2021-06-28 05:44 UTC, Mark-Fenng commented
@Yuyz0112 How do you like the choice of package manager? Workspaces, lerna or pnpm

2021-07-22 15:59 UTC, Mark-Fenng commented
This PR is almost done except for a build warning.
Tips:
1. Because we want to keep the commit history of the other two projects, the number of commits in this PR may be a little too much. And because of the same reason, when merging this PR, we should __avoid the squash operation__.
2. I think we can keep using yarn workspace as our package manager for now and it's not hard to replace it with another manager if yarn can't meet our requirement later.
3. There's still a build warning as follows in the rrweb-player package.
```
(!) Unresolved dependencies
[https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency)
rrweb (imported by src/Player.svelte, src/Controller.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
rrweb (guessing 'rrweb')
created public/bundle.js in 1.8s
```
It seems like its rollup config doesn't fit for monorepo environment and any help would be great.

2021-07-22 20:56 UTC, Juice10 requested changes
Looking really good @Mark-Fenng! I found some very minor outdated urls, but apart from that this looks good!

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-snapshot/README.md
> +[![Build Status](https://travis-ci.org/rrweb-io/rrweb-snapshot.svg?branch=master)](https://travis-ci.org/rrweb-io/rrweb-snapshot) [![Join the chat at https://gitter.im/rrweb-io/rrweb-snapshot](https:
Build status icon should be changed to this repo
```suggestion
[![Build Status](https://travis-ci.org/rrweb-io/rrweb.svg?branch=master)](https://travis-ci.org/rrweb-io/rrweb) [![Join the chat at https://gitter.im/rrweb-io/rrweb-snapshot](https://badges.gitter.im/rrweb-io/rrweb-snapshot.svg)](https://gitter.im/rrweb-io/rrweb-snapshot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-snapshot/package.json
> +    "url": "https://github.com/rrweb-io/rrweb-snapshot/issues"
```suggestion
    "url": "https://github.com/rrweb-io/rrweb/issues"
```

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-snapshot/package.json
> +  "homepage": "https://github.com/rrweb-io/rrweb-snapshot#readme",
```suggestion
  "homepage": "https://github.com/rrweb-io/rrweb#readme",
```

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-player/package.json
> +    "url": "https://github.com/rrweb-io/rrweb-player/issues"
```suggestion
    "url": "https://github.com/rrweb-io/rrweb/issues"
```

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-player/package.json
> +    "url": "git+https://github.com/rrweb-io/rrweb-player.git"
```suggestion
    "url": "git+https://github.com/rrweb-io/rrweb.git"
```

2021-07-22 20:56 UTC, Juice10 commented on packages/rrweb-player/package.json
> +  "homepage": "https://github.com/rrweb-io/rrweb-player#readme"
```suggestion
  "homepage": "https://github.com/rrweb-io/rrweb#readme"
```

2021-07-23 04:36 UTC, Juice10 approved these changes

2021-07-23 15:00 UTC, Yuyz0112 commented
Nice! Let's go.

I think contributors may see some conflicts in their existing PRs, we can help them get things done again.

And I'm going to check the rollup things and update the release script.

Awesome work.

2021-07-23 15:01 UTC, merged