DragEvent handling, null check fixes
rrweb-io/rrweb pull request #630
Opened 2021-07-13 20:55 UTC by dbseel

* fix the thrown error caused by DragEvent variable not being defined on some devices/browsers
* add additional node and shadowHost null checks to fix thrown errors

2021-07-13 20:59 UTC, IMFIL commented
@Yuyz0112 We use a fork of rrweb with this change and this PR fixed bugs that we saw happen to millions of our users.

2021-07-19 10:16 UTC, Juice10 requested changes

2021-07-19 10:16 UTC, Juice10 commented on src/record/mutation.ts
>            const _node = addList.get(index)!;
Since we are no longer expecting `_node` to always have a value, let's remove the `!` which marks it as non-null.
```suggestion
          const _node = addList.get(index);
```

2021-07-19 10:17 UTC, Juice10 approved these changes

2021-07-19 10:32 UTC, Yuyz0112 commented on src/record/mutation.ts
> +        (!(shadowHost instanceof Node) || !this.doc.contains(shadowHost));
just curious, what shadow host will be if it's not a Node?

2021-07-19 10:32 UTC, Yuyz0112 commented on src/record/mutation.ts
> +          // ensure _node is defined before attempting to find value
I'm not sure when do you facing this problem, because I think the root cause has been fixed in https://github.com/rrweb-io/rrweb/commit/2c6be72f35f68513b0d511a37037018663cbc704

So we should not get a node with value null in this linked list anymore?

2021-07-19 12:57 UTC, dbseel commented on src/record/mutation.ts
> +        (!(shadowHost instanceof Node) || !this.doc.contains(shadowHost));
It can be null, see line 271

2021-07-19 12:57 UTC, dbseel commented on src/record/mutation.ts
> +          // ensure _node is defined before attempting to find value
We encountered this problem using a version or rrweb that included that commit.

2021-07-19 13:35 UTC, Yuyz0112 commented on src/record/mutation.ts
> +          // ensure _node is defined before attempting to find value
if so, I believe we should debugging into the issue because skip one node of the linked list can cause potential data loss.

2021-07-31 07:18 UTC, merged

2021-08-03 15:11 UTC, eoghanmurray commented
Why is the `typeof DragEvent` check done outside of the `updatePosition` function?  Why not do something like

        typeof DragEvent !== 'undefined' && evt instanceof DragEvent
          ? IncrementalSource.Drag
          : evt instanceof MouseEvent
          ? IncrementalSource.MouseMove
          : IncrementalSource.TouchMove;

?

I'm trying to reconcile this commit with https://github.com/rrweb-io/rrweb/pull/558/commits/97c36393cfc2e92bb8e86851cce5d142d65fdbc5 and the separation into two functions is leading to a lot of further code duplication.  The `evt instanceof DragEvent` clause seems to be the only bit that is different between `updateDragPosition` and `updatePosition`

2021-08-04 15:11 UTC, dbseel commented
> Why is the `typeof DragEvent` check done outside of the `updatePosition` function? Why not do something like
> 
> ```
>     typeof DragEvent !== 'undefined' && evt instanceof DragEvent
>       ? IncrementalSource.Drag
>       : evt instanceof MouseEvent
>       ? IncrementalSource.MouseMove
>       : IncrementalSource.TouchMove;
> ```
> 
> ?
> 
> I'm trying to reconcile this commit with [97c3639](https://github.com/rrweb-io/rrweb/commit/97c36393cfc2e92bb8e86851cce5d142d65fdbc5) and the separation into two functions is leading to a lot of further code duplication. The `evt instanceof DragEvent` clause seems to be the only bit that is different between `updateDragPosition` and `updatePosition`
> 
> [edit I've added #652 to show this idea]

They prototype of the call itself was causing problems when DragEvent wasn't defined. That is why the check is done ahead of the function call.