Monkeypatch each iframe
rrweb-io/rrweb pull request #716
Opened 2021-09-29 11:22 UTC by eoghanmurray

observers which worked by monkeypatching built in objects were not working within iFrames as these have their own clean window object which doesn't include the iframe

2021-09-29 11:24 UTC, Yuyz0112 commented
Also found these bugs, good job 👍 . Going to review in the coming holiday.

2021-09-29 11:46 UTC, Juice10 requested changes

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +    [key: string]: win.GroupingCSSRuleTypes;
This is a type, no need to prefix that
```suggestion
    [key: string]: GroupingCSSRuleTypes;
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +      deleteRule: (type as win.GroupingCSSRuleTypes).prototype.deleteRule,
Also types
```suggestion
      insertRule: (type as GroupingCSSRuleTypes).prototype.insertRule,
      deleteRule: (type as GroupingCSSRuleTypes).prototype.deleteRule,
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +    this: win.CSSStyleDeclaration,
Also a type
```suggestion
    this: CSSStyleDeclaration,
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +    this: win.CSSStyleDeclaration,
Also a type
```suggestion
    this: CSSStyleDeclaration,
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +          prop as keyof win.CanvasRenderingContext2D
Type
```suggestion
          prop as keyof CanvasRenderingContext2D
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +            this: win.CanvasRenderingContext2D,
Type
```suggestion
            this: CanvasRenderingContext2D,
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +      const hookHandler = hookSetter<win.CanvasRenderingContext2D>(
Also type
```suggestion
      const hookHandler = hookSetter<CanvasRenderingContext2D>(
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +    curr_window,
JavaScript conventions
```suggestion
  const currentWindow = o.doc.defaultView,  // basically document.window

  const styleSheetObserver = initStyleSheetObserver(
    o.styleSheetRuleCb,
    currentWindow,
    o.mirror,
  );
  const styleDeclarationObserver = initStyleDeclarationObserver(
    o.styleDeclarationCb,
    currentWindow,
```

2021-09-29 11:46 UTC, Juice10 commented on packages/rrweb/src/record/observer.ts
> +      curr_window,
```suggestion
      currentWindow,
```

2021-09-29 12:03 UTC, eoghanmurray commented
Working on the typings suggestions from Justin, thanks @Juice10!

2021-09-29 14:11 UTC, eoghanmurray commented on packages/rrweb/src/record/observer.ts
> +    curr_window,
Thanks! My bad.

2021-09-29 14:12 UTC, eoghanmurray commented
Thanks @Juice10 I think all the review suggestions have been incorporated with the last force-push

2021-10-01 06:55 UTC, Yuyz0112 commented
LGTM, and I will send a PR try to reduce the usage of `(win as any)`

2021-10-01 06:56 UTC, merged