Save images offline, in the snapshot
rrweb-io/rrweb pull request #770
Opened 2021-12-14 16:28 UTC by croqaz

Hi guys,

I made this feature that I already discussed here: https://github.com/rrweb-io/rrweb/issues/737
It's about saving images inside the snapshot as base64, just like we have for canvas already.

I tried to use the same code style and not change things too much.
I added a test, but I'm not sure if it's in the right place. In the integration, it seemed the best place, because you're using Puppeteer and we need to simulate a canvas to make it work.

Please let me know if you think something is wrong, or you want more tests, or I'm missing something.

2021-12-14 16:44 UTC, croqaz commented on packages/rrweb-snapshot/src/rebuild.ts
> +              image.setAttribute('data-src', image.currentSrc);
Here I used the `data-src` attribute for keeping the original URL.
Maybe we can use something else, less likely to conflict, maybe `data-rr-src` ? or `data-rrweb-src` ?
What do you think?

2021-12-14 16:53 UTC, croqaz commented on packages/rrweb-snapshot/src/rebuild.ts
> +              image.setAttribute('data-src', image.currentSrc);
OK I just went ahead and renamed this to `data-rrweb-src`.

2021-12-26 12:35 UTC, Yuyz0112 requested changes
Very cool feature! Thanks!

2021-12-26 12:35 UTC, Yuyz0112 commented on guide.md
> +| recordImages         | false              | whether to record the image content
maybe inlineImages or something more concrete?

2021-12-26 12:35 UTC, Yuyz0112 commented on packages/rrweb-snapshot/src/snapshot.ts
> +      if (tagName === 'img' && recordImages && canvasService && canvasCtx) {
To avoid some corner cases in the browser, especially some security options with cross-origin domains, how about adding a try-catch to this block? So even though corner cases happen, it will not block the recording.

2022-01-04 13:50 UTC, croqaz commented on guide.md
> +| recordImages         | false              | whether to record the image content
Sure! Done!

2022-01-04 13:51 UTC, croqaz commented on packages/rrweb-snapshot/src/snapshot.ts
> +      if (tagName === 'img' && recordImages && canvasService && canvasCtx) {
Not sure if I understood where you want the try catch, I added it a little below.
See https://github.com/rrweb-io/rrweb/pull/770/commits/cec7fdae383e5cd8ddb9686d7c4fb264a519e217#diff-6434d77e679a3d1e4217dcad03ee6f02551e41dc0b077a06a45020e68e1b4ee3R519-R526

2022-01-10 12:00 UTC, lopuhin commented on packages/rrweb-snapshot/src/snapshot.ts
> +          // ignore error
shall we log something here, e.g. with ``console.warn``?

2022-01-11 15:54 UTC, Yuyz0112 commented
Sorry for the late, let's go!

2022-01-11 15:54 UTC, merged

2024-05-07 08:12 UTC, eoghanmurray commented
@croqaz could you check out #1468 for me?  This builds on top of subsequent work in #822