Update css-font-loading-module
rrweb-io/rrweb pull request #784
Opened 2021-12-22 20:45 UTC by gabrielstellini

Updates css-font-loading-module from `0.0.4` to `0.0.7`.

2021-12-23 09:37 UTC, Juice10 requested changes

2021-12-23 09:37 UTC, Juice10 commented on packages/rrweb/src/types.ts
> -import { FontFaceDescriptors } from 'css-font-loading-module';
Why are you removing the `FontFaceDescriptors` import? 

Looks like it would break the code since `FontFaceDescriptors` is still being referenced later on in the file: https://github.com/rrweb-io/rrweb/blob/c70b32870e597b99b8db6d20fc012f977dea8c21/packages/rrweb/src/types.ts#L445

2022-01-25 23:37 UTC, jtheberge commented on packages/rrweb/src/types.ts
> -import { FontFaceDescriptors } from 'css-font-loading-module';
Can we use typescript's DOM lib definition here instead to avoid interface duplicate naming conflicts?
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L491
Assuming that's why it can be safely deleted here.
Relevant issue: #813

2022-01-26 00:04 UTC, gabrielstellini commented on packages/rrweb/src/types.ts
> -import { FontFaceDescriptors } from 'css-font-loading-module';
@jtheberge If it's urgent, I recommend using `patch-package` to fix this issue (temporarily). Here's the contents of my  `patches/rrweb+1.0.7.patch` file:

```
diff --git a/node_modules/rrweb/typings/types.d.ts b/node_modules/rrweb/typings/types.d.ts
index 7d9c049..4bfd2ea 100644
--- a/node_modules/rrweb/typings/types.d.ts
+++ b/node_modules/rrweb/typings/types.d.ts
@@ -1,6 +1,5 @@
 import { serializedNodeWithId, idNodeMap, INode, MaskInputOptions, SlimDOMOptions, MaskInputFn, MaskTextFn } from 'rrweb-snapshot';
 import { PackFn, UnpackFn } from './packer/base';
-import { FontFaceDescriptors } from 'css-font-loading-module';
 import { IframeManager } from './record/iframe-manager';
 import { ShadowDomManager } from './record/shadow-dom-manager';
 import type { Replayer } from './replay';
```

2022-01-26 00:22 UTC, jtheberge commented on packages/rrweb/src/types.ts
> -import { FontFaceDescriptors } from 'css-font-loading-module';
ah nice idea, hadn't heard of this before but appreciate the info!

2022-01-27 14:55 UTC, Yuyz0112 commented
Thanks, going to merge this and have a try by myself.

2022-01-27 14:55 UTC, merged