isBlocked factors in the selector
rrweb-io/rrweb pull request #894
Opened 2022-05-11 16:09 UTC by dbseel

Support a list of blocked classes in a CSS selector (blockSelector) in addition to the blockClass.

2022-05-30 16:11 UTC, IMFIL commented
@Yuyz0112 Hey man, we've added a bunch of changes to Rrweb as we are using it on thousands of websites and noticed some flaws. Let us know if certain things are missing for this to get merged in.

2022-05-30 22:30 UTC, Juice10 commented
Thanks for the PR @dbseel! When refactoring and speeding up `isBlocked` for https://github.com/rrweb-io/rrweb/pull/903 I also noticed this was missing from rrweb. Happy you've created a PR for it.
Because https://github.com/rrweb-io/rrweb/pull/903 has checked the guts of `isBlocked` drastically I expect it to create some merge issues for this branch once it gets merged in.

2022-08-19 10:01 UTC, Juice10 commented
Hey @dbseel, any chance you could fix the merge issues?

2022-08-19 16:20 UTC, dbseel commented
@Juice10 Done. Can we get this merged in? It has been sitting here 3 months, don't want to have to rebase again.

2022-08-20 08:33 UTC, Juice10 requested changes
Thanks for rebasing @dbseel, apologies that this has been sitting for so long. Thank you for your fixes! I'm going to do my best to get this merged ASAP for you

I noticed `ignoreCSSAttributes` isn't documented yet in https://github.com/rrweb-io/rrweb/blob/5f59f9171e481c78d08a1008186cff31a40ee199/guide.md#options could you add one to `guide.md` and a placeholder (or maybe google translated) to the Chinese [`guide.zh_CN.md`](https://github.com/rrweb-io/rrweb/blob/5f59f9171e481c78d08a1008186cff31a40ee199/guide.zh_CN.md#配置参数)

2022-08-20 08:33 UTC, Juice10 commented on packages/rrweb-snapshot/src/snapshot.ts
>  }
This reverts the performance optimizations from https://github.com/rrweb-io/rrweb/pull/903 and I'm not quite sure what extra functionality this brings.

2022-08-20 08:33 UTC, Juice10 commented on packages/rrweb/src/utils.ts
> +  }
If `checkAncestors` is true we should also check to see if any of the parents of this node are blocked

```suggestion
  if (blockSelector) {
    if ((node as HTMLElement).matches(blockSelector)) return true;
    if (checkAncestors && el.closest(blockSelector) !== null) return true;
  }
```

2022-08-20 08:33 UTC, Juice10 commented on packages/rrweb/src/utils.ts
> +  return isBlocked(node.parentNode, blockClass, blockSelector, checkAncestors);
Parents where already checked if `checkAncestors` was set to true, no need to go further up the tree
```suggestion
  return false;
```

2022-08-20 08:33 UTC, Juice10 commented on packages/rrweb-snapshot/src/snapshot.ts
>  }
This reverts the performance optimizations from https://github.com/rrweb-io/rrweb/pull/903 and I'm not quite sure what extra functionality this brings.

Maybe we should revert this code?

2022-08-29 19:27 UTC, Juice10 approved these changes
Thanks for this @dbseel! Really appreciate your contribution. Apologies that it took so long for us to review it

2022-08-29 19:29 UTC, dbseel commented
> Thanks for this @dbseel! Really appreciate your contribution. Apologies that it took so long for us to review it

No problem! Are you able to merge? I don't have permissions.

2022-08-29 21:08 UTC, Juice10 commented
I don't but I've messaged the other members of the core team, so it should get merged soon

2022-08-30 05:27 UTC, Yuyz0112 approved these changes
good job!

2022-08-30 05:27 UTC, merged

2023-02-28 16:15 UTC, eoghanmurray commented
Late to the party here!

@dbseel what are the use cases for `ignoreCSSAttributes`?  I see `color` in the test case but curious as to the others.  Is the motivation for this privacy, or performance (like slimDOM options).

Also wondering whether `ignoreCSSProperties` would have been a better name?

2023-02-28 16:22 UTC, dbseel commented
> @dbseel what are the use cases for `ignoreCSSAttributes`?
We have encountered some websites where certain attributes were constantly being added/removed/added to the DOM, but they did not affect the replay. So there was a huge performance improvement by ignoring these attributes.

2023-03-01 16:17 UTC, eoghanmurray commented
These are CSS rule attributes rather than DOM attributes though?
I guess just thinking it must be very unusual that rules would be continually added/removed.
Was it a standard part of some framework, or just some once off craziness on a particular website?

2023-03-01 18:36 UTC, dbseel commented
> These are CSS rule attributes rather than DOM attributes though? I guess just thinking it must be very unusual that rules would be continually added/removed. Was it a standard part of some framework, or just some once off craziness on a particular website?

In our case a website was using quantum metrics. This plugin was adding/removing attributes thousands of times a second. Attributes like this: --quantum-metric-background-image

2024-04-30 13:36 UTC, eoghanmurray commented
I've just come across this again today; I notice that `ignoreCSSAttributes` doesn't omit them from capture from the initial snapshot. This wouldn't be significant for your usecase of mutations to `--quantum-metric-background-image`, but for completeness does anyone think it needs to be added?