rrweb: add selection observer
rrweb-io/rrweb pull request #936
Opened 2022-07-12 03:44 UTC by 0jinxing

support selection change record and replay

2022-07-25 03:05 UTC, Yuyz0112 commented
@0jinxing Thanks! This looks interesting, could you provide more information about the use case of this feature, and a short video demo for the replay effect?

BTW, e2e test cases are required.

2022-07-31 06:03 UTC, Mark-Fenng commented
@0jinxing Thanks for your excellent feature contribution.
I made a simple demo with your code and the effect is fantastic!

https://user-images.githubusercontent.com/27533910/182012487-ea2fb651-36df-417b-bb1b-c417da42710b.mp4


https://user-images.githubusercontent.com/27533910/182012492-214e4026-7b37-470c-838b-e4cc293f9f28.mp4

I am looking forward to seeing the complementation and merge of this PR!

2022-07-31 07:04 UTC, Mark-Fenng requested changes

2022-07-31 07:52 UTC, Mark-Fenng requested changes

2022-07-31 07:52 UTC, Mark-Fenng commented on packages/rrweb/src/replay/index.ts
> +        ranges.forEach((r) => r && selection?.addRange(r));
```suggestion
        const selectionSet = new Set<Selection>();
        const ranges = d.ranges.map(
          ({ start, startOffset, end, endOffset }) => {
            const startContainer = this.mirror.getNode(start);
            const endContainer = this.mirror.getNode(end);

            if (!startContainer || !endContainer) return;

            const result = new Range();

            result.setStart(startContainer, startOffset);
            result.setEnd(endContainer, endOffset);
            const doc = startContainer.ownerDocument;
            const selection = doc?.getSelection();
            selection && selectionSet.add(selection);

            return {
              range: result,
              selection,
            };
          },
        );

        selectionSet.forEach((s) => s.removeAllRanges());

        ranges.forEach((r) => r && r.selection?.addRange(r.range));
```
One more issue is that if the recorded selection change is inside an IFrame element, the selection target should be changed to iframe's selection.

2022-07-31 07:52 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +    const selection = document.getSelection();
```suggestion
    const selection = doc.getSelection();
```
If the website has an iframe element, the document has to be iframe's document and it can be retrieved from the param.

2022-07-31 07:52 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +  const { mirror, blockClass, selectionCb } = param;
```suggestion
  const { doc, mirror, blockClass, selectionCb } = param;
```

2022-08-03 01:27 UTC, 0jinxing commented on packages/rrweb/src/record/observer.ts
> +  let collapsed = true;
when it is not selected, clicking will also trigger
filter some useless event

2022-08-03 01:55 UTC, 0jinxing commented on packages/rrweb/src/record/observer.ts
> +    const selection = document.getSelection();
yeah. this would be more appropriate

2022-08-03 02:22 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +    const selection = document.getSelection();
Got it, thanks for your explanation

2022-08-03 02:23 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +  let collapsed = true;
Got it, thanks for your explanation

2022-08-03 09:54 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +    const selection = document.getSelection();
@0jinxing I guess you may miss this one

2022-08-03 11:04 UTC, Mark-Fenng commented on packages/rrweb/test/utils.ts
> +export const sampleSelectionEvents: eventWithTime[] = [
All test cases look good but I'd recommend defining and importing events like this: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/test/events/style-sheet-rule-events.ts.  Content of the sample events looks great but just because this is no longer our best practice for test events.

2022-08-03 13:08 UTC, 0jinxing commented on packages/rrweb/test/utils.ts
> +export const sampleSelectionEvents: eventWithTime[] = [
🫣🫣

2022-08-03 13:41 UTC, Mark-Fenng approved these changes
@0jinxing Thanks for your quick modification and reply! Hope to see it merged soon.

2022-08-06 08:59 UTC, Yuyz0112 commented
Thanks, let's merge it!

2022-08-06 08:59 UTC, merged

2022-12-15 11:03 UTC, eoghanmurray commented on packages/rrweb/src/record/observer.ts
> +  return on('selectionchange', updateSelection);
The `on` function here expects a third 'target' argument; I presume it should be `doc`?

2023-01-18 12:12 UTC, eoghanmurray commented on packages/rrweb/src/record/observer.ts
> +  return on('selectionchange', updateSelection);
@0jinxing can you confirm that it should be `doc` passed as the third argument?  
Otherwise it's trying to `addEventListener` on `undefined`

2023-03-31 15:03 UTC, eoghanmurray commented on packages/rrweb/src/record/observer.ts
> +  return on('selectionchange', updateSelection);
@YunFeng0817 I'm not sure how this has escaped everyone's notice if it's been merged!