fix: canvas data in iframe wasn't applied in the fast-forward mode
rrweb-io/rrweb pull request #944
Opened 2022-07-24 06:53 UTC by Mark-Fenng

In #853, I implemented the virtual dom for the fast-forward mode.  But there is a corner case I didn't deal with.
If a canvas element is created with image data (serialized to `rr_dataURL`) in an iframe, it will be rebuilt as an empty canvas without the initial image data, in the fast-forward mode (using Virtual Dom optimization).
A simple test case is also added in this PR to reproduce this corner case.

2022-07-25 06:10 UTC, Juice10 requested changes
Good catch! Found one little tweak to make the code slightly more robust

2022-07-25 06:10 UTC, Juice10 commented on packages/rrdom/src/diff.ts
> +              };
These should be flipped to insure onload isn't called before the event handler gets added
```suggestion
              image.onload = () => {
                const ctx = (oldElement as HTMLCanvasElement).getContext('2d');
                if (ctx) {
                  ctx.drawImage(image, 0, 0, image.width, image.height);
                }
              };
              image.src = rrCanvasElement.rr_dataURL;
```

2022-07-25 08:14 UTC, Mark-Fenng commented on packages/rrdom/src/diff.ts
> +              };
Flipped one is more straightforward for sure. But I suddenly realize that according to the JS engine's execution mechanism, I think the onload callback won't be called before the function definition. 
image.onload = ... definition is synchronous while the onload callback is asynchronous so that the callback will be always invoked after the function definition.

2022-07-31 01:00 UTC, Yuyz0112 approved these changes

2022-07-31 01:01 UTC, merged