feat: add support for recording and replaying adoptedStyleSheets API
rrweb-io/rrweb pull request #989
Opened 2022-09-07 08:44 UTC by Mark-Fenng

## Background

The **adoptedStyleSheets** property of the Document or shadowRoot is used for setting an array of constructed stylesheets to be used by the host. reference: [https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets)

Nowadays, more and more web libraries and pages are using custom web components and this API like [Lit](https://lit.dev/), [material wc](https://material-components.github.io/material-web/demos/button/). There’s also a related issue #669.

## Implementation

This PR mostly follows @Yuyz0112's  proposal: [https://github.com/rrweb-io/rrweb/issues/669#issuecomment-937522437](https://github.com/rrweb-io/rrweb/issues/669#issuecomment-937522437). 

I create a StyleMirror which is similar to Node Mirror that we used to manage nodes and their serialized ids. In the recording side, if I get a constructed stylesheet from adoptedStyleSheets API, firstly ask StyleMirror whether it appears before or not. If it’s a new stylesheet, I add it to the StyleMirror, assign a new unique styleId, and serialize it into an event. 

Here’s an example event to serialize a new stylesheet object:

```tsx
{
  type: EventType.IncrementalSnapshot,
  data: {
    source: IncrementalSource.AdoptedStyleSheet,
    id: 1, // id indicates the node id of document or shadow DOMs' host element.
		// serialize the new stylesheet
		styles: [
      {
        rules: [
          {
            rule: 'div { color: yellow; }',
          },
        ],
        styleId: 1,
      },
    ],
    styleIds: [1], // style ids of adopted stylesheets
  }
}
```

If it already has a styleId, I will reference (reuse) it directly like this:

```tsx
{
  type: EventType.IncrementalSnapshot,
  data: {
    source: IncrementalSource.AdoptedStyleSheet,
    id: 1, // id indicates the node id of document or shadow DOMs' host element.
    styleIds: [1], // reference styleIds directly
  }
}
```

On the replaying side, I deserialize stylesheet objects from events and assign them to the target documents.

## Changes

1. add a new incremental event type: AdoptedStyleSheet.
2. change the current styleSheetRule and styleDeclaration event and make them support tracking mutation of adoptedStyleSheets.
3. totally remove virtualStylesheet from rrdom to reduce duplicate code
4. add support for [replace](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replace) and [replaceSync](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replaceSync) APIs
5. refactor stylesheet-manager and move the main code of adopedStylesheets into it.
6. 5 test cases (3 on the recording side and 2 on the replaying side)
7. StyleMirror implementation and unit tests
8. refactor the stylesheet part in the replayer and add support for VirtualDom optimization

## Other things

Because adoptedStypeSheets is a new API, there is a browser compatibility issue for the replaying side. The replayer can replay adoptedStyleSheet events only when the browser supports the API. reference: [https://caniuse.com/?search=adoptedStyleSheets](https://caniuse.com/?search=adoptedStyleSheets)

Special thanks to @lele0108 's sponsorship for making this pull request possible.

## Effect
### Before this PR:

https://user-images.githubusercontent.com/27533910/188832637-cf87e5e8-178d-4e02-a4fd-6991df04bec2.mp4

### After this PR applied:

https://user-images.githubusercontent.com/27533910/188832739-0ce45aac-a079-4a8a-9b1d-72412eb2e31f.mp4

2022-09-08 13:48 UTC, Mark-Fenng commented
@dbseel  This PR is relatively huge and it may take some time for Yuyz and Justin to review. I believe that it will get merged finally.

2022-09-08 14:00 UTC, Yuyz0112 reviewed
Very exciting PR 👍 

Some minor tweaks and the defer solution may need to be verified in the real world. @Mark-Fenng feel free to merge this when you change the requests.

2022-09-08 14:00 UTC, Yuyz0112 commented on packages/rrweb-snapshot/src/rebuild.ts
> +    mirror.replace(n.rootId, doc);
I think this is still need because legacy events may have this issue.

2022-09-08 14:00 UTC, Yuyz0112 commented on packages/rrweb/src/record/observer.ts
> +function getIdOrStyleId(
`getIdOrStyleId` -> `getIdAndStyleId`?

2022-09-08 15:13 UTC, Mark-Fenng commented
Thanks for the suggestions. There are many changes related to @Juice10's code base. I'll merge it after his review.

2022-09-16 14:18 UTC, Juice10 requested changes
What a great addition to rrweb, thanks for that @Mark-Fenng!
I am however concerned about Safari and breaking playback in that browser, we currently aren't using any polyfills to add support for it in the playback. And on record we could also be breaking things there since we're setting properties which would otherwise be empty, preventing people from doing feature detection.
I made this mistake myself once in the past when building the first iteration of the stylesheet manager and I really wanted to add https://github.com/amilajack/eslint-plugin-compat to the project but as we where using tslint back then instead of eslint I wasn't able to. Maybe this is a good moment to add it since we are using eslint at the moment.

2022-09-16 14:18 UTC, Juice10 commented on packages/rrweb/src/record/constructableStyleSheets.d.ts
> +  adoptedStyleSheets: CSSStyleSheet[];
Since this is not always available (no current or pre-release version of safari supports it for example) it might make sense to add it as an 'optional' parameter
```suggestion
  adoptedStyleSheets?: CSSStyleSheet[];
```

2022-09-16 14:18 UTC, Juice10 commented on packages/rrweb/src/record/constructableStyleSheets.d.ts
> +}
Same for these
```suggestion
declare interface CSSStyleSheet {
  replace(text: string)?: Promise<CSSStyleSheet>;
  replaceSync(text: string)?: void;
}
```

2022-09-16 14:18 UTC, Juice10 commented on packages/rrweb/src/record/constructableStyleSheets.d.ts
> +// This informs the TS compiler about constructed stylesheets.
So far we've mostly used kebab-case for file names. This file is deviating from that. Probably makes sense to rename it to `constructible-style-sheets.d.ts`

2022-09-16 14:18 UTC, Juice10 commented on packages/rrweb/src/replay/index.ts
> +      newStyleSheet = new hostWindow.CSSStyleSheet();
This will break Safari playback without a polyfill

2022-09-17 05:41 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +  });
I think https://github.com/rrweb-io/rrweb/pull/989/files/ca9da9a9e2fe2190768db364bf5f6a3a53673bf9#diff-b7a42c375ac5ab2de196b5e95e0b2f82b723969c5836fac0ff6f7ca6ad66ebd7R753 this line can check the existence of the API.

2022-09-17 05:57 UTC, Mark-Fenng commented
@Juice10 Geat catches on compatibility issues of these APIs. I also added the eslint-plugin-compat and configured the browser list for each package. 
If some APIs are rarely used in the package, and they are polyfilled or have a workaround in older browsers, I think this lint rule can be disabled. Otherwise, the browser list has to be updated.

2022-09-26 15:39 UTC, Juice10 commented on packages/rrweb/src/record/index.ts
> +                  // eslint-disable-next-line compat/compat
This PR fixes all these issues: https://github.com/rrweb-io/rrweb/pull/1010

2022-09-26 15:39 UTC, Juice10 commented on packages/rrweb/src/record/index.ts
> +                  // eslint-disable-next-line compat/compat
Fixed by: https://github.com/rrweb-io/rrweb/pull/1010

2022-09-26 15:40 UTC, Juice10 commented on packages/rrweb/src/record/index.ts
> +                  // eslint-disable-next-line compat/compat
Fixed by: https://github.com/rrweb-io/rrweb/pull/1010

2022-09-29 06:14 UTC, Juice10 approved these changes
Great work @Mark-Fenng! Thanks for the changes, I think this is a great addition to rrweb

2022-09-29 06:40 UTC, merged