fix: iframe input hook (#990)
rrweb-io/rrweb pull request #991
Opened 2022-09-08 01:35 UTC by luocongqiu

2022-09-08 03:05 UTC, Mark-Fenng requested changes
@luocongqiu Thanks for your contribution both on the issue and pull request. Your pull request looks great.

2022-09-08 03:05 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +  const currentWindow = doc.defaultView;
The code all looks good to me. Only a code format (using prettier) is required.

2022-09-08 13:49 UTC, Yuyz0112 approved these changes
good catch!

2022-09-08 13:51 UTC, Mark-Fenng approved these changes

2022-09-08 15:03 UTC, Mark-Fenng commented on packages/rrweb/src/record/observer.ts
> +        }, false, currentWindow),
@luocongqiu Seems like there's also a format problem.
Please execute `yarn prettier --write '**/*.{ts,md}'` to fix them all.

2022-09-09 01:08 UTC, luocongqiu commented on packages/rrweb/src/record/observer.ts
> +        }, false, currentWindow),
@Mark-Fenng thanks，I've formatted the code

2022-09-09 03:25 UTC, merged