Fix inline link elements bug
rrweb-io/rrweb pull request #995
Opened 2022-09-11 04:46 UTC by Mark-Fenng

In PR #909, an async mechanism for inlining link elements is introduced but it still has a bug and some negative impacts on the replayer side.

### The Bug
In the stylesheet-manager.ts, when the link element loaded the styles, the manager emits an incremental mutation event to inline styles. But the mutation's parentId is wrong. https://github.com/rrweb-io/rrweb/blob/abc035fd00972c3ffa1a9cf379b46f53cb74d394/packages/rrweb/src/record/stylesheet-manager.ts#L34
As a result, the event looks like this: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/27533910/189511629-cbb0f229-2167-41bf-b949-2b756bcab3d4.png"> https://github.com/rrweb-io/rrweb/compare/master...fix-inline-link-elements#diff-988864050cbe6d85b4cb140a06ffce65819d8967e071b175f1d27b8a864b5383L176-L189
The parentNode of the link element is itself and it can't be appended to the dom actually.

### Negative Impacts
This mechanism makes elements absent in the normal snapshot stage and causes performance issues and many warnings in the console.
Here's a diagram to explain this problem.

![explanation](https://user-images.githubusercontent.com/27533910/189512099-78120d7c-259a-4bea-9475-2e5672a99b1f.svg)

<img width="540" alt="image" src="https://user-images.githubusercontent.com/27533910/189512834-08369d55-876b-4e71-a010-7f46a44bdd9d.png">

### Changes

I built this PR based on #989 so that it contains all changes of that PR. **This PR has to get merged after #989**.
I made some changes to the current mechanism. In the snapshot stage, the unloaded Link elements will still get serialized without inline styles. After they are loaded. an incremental mutation of attributes is appended which includes an attribute `_cssText`. Its value is the inlined CSS styles. 
```ts
{
  source: IncrementalSource.Mutation,
  adds: [],
  removes: [],
  texts: [],
  attributes: [
    {
      id: 9,
      attributes: {
        _cssText: "body { color: pink; }",
      },
    },
  ],
}
```
This way, the unloaded Link elements can be inlined without causing the above-mentioned side effects.
On the replaying side, when the replayer encounters the '_cssText' attribute change and its target is the Link element, the replayer can replace the old un-inlined one with the inlined loaded Link element.
This method can make it easy to implement the TODO feature as well. https://github.com/rrweb-io/rrweb/blob/abc035fd00972c3ffa1a9cf379b46f53cb74d394/packages/rrweb/src/record/stylesheet-manager.ts#L19-L24 

This PR can also fix #981.

2022-09-16 14:23 UTC, Juice10 commented on packages/rrdom/src/index.ts
> +    }
If replace gets called but there is nothing to replace, the old behaviour added that node to the idNodeMap, the new behaviour does not. I'm not sure if this is good or bad, maybe it should produce a warning if there is no node available in case we messed up somewhere.

2022-09-16 14:25 UTC, Juice10 commented on packages/rrweb/src/record/stylesheet-manager.ts
> +    if ('_cssText' in (childSn as elementNode).attributes)
Is `_cssText` always going to be set, also if a link element hasn't finished loading yet?

2022-09-16 14:39 UTC, Juice10 requested changes
Thanks for finding and fixing this bug! I found a one bug and maybe another potential bug. Could you fix those and I'd be happy to re-review & approve!

2022-09-16 14:39 UTC, Juice10 commented on packages/rrweb/src/replay/index.ts
> +                  }
In this case we are replacing an existing Link or probably Style element with a new Style element with the updated css. However we don't seem to be keeping around the existing attributes on that element. That means that if someone set `media="print"` on their stylesheet, that will essentially get wiped off and will effectively work as if it was  `media="all"`. This could break some websites

2022-09-16 14:39 UTC, Juice10 commented on packages/rrdom/src/index.ts
> +    }
```suggestion
    const oldNode = this.getNode(id);
    if (oldNode) {
      const meta = this.nodeMetaMap.get(oldNode);
      if (meta) this.nodeMetaMap.set(n, meta);
      this.idNodeMap.set(id, n);
    } else {
      console.warn(`Mirror tried to replace node with id: ${id}, but no node exists with that id`);
    }
```

2022-09-17 07:03 UTC, Mark-Fenng commented on packages/rrweb/src/record/stylesheet-manager.ts
> +    if ('_cssText' in (childSn as elementNode).attributes)
According the code below https://github.com/rrweb-io/rrweb/blob/08ab7ab45227a31f3f35e2ff43e6517f567130b2/packages/rrweb-snapshot/src/snapshot.ts#L653-L659
I think it will set _cssText when the link has been loaded. Otherwise, recorder will only keep its original attributes.

2022-09-17 07:38 UTC, Mark-Fenng commented on packages/rrweb/src/replay/index.ts
> +                  }
Good catch, I add the code to keep their existing attributes before rebuilding the elements.

2022-09-23 00:52 UTC, Mark-Fenng commented
Today I encountered an issue with the replayer also caused by this.

This is the link element on the recorder side.
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/27533910/191874613-8aca2cd9-d560-4e03-bce7-02ae0dd21f2b.png">

While this screenshot is the link element on the replayer side.
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/27533910/191874697-a7a1bb7f-bef5-4b0f-8954-ebeaeddb9399.png">
The element is self-nested in 4 depths.

2022-09-29 07:37 UTC, Mark-Fenng commented
I rebased the latest master branch and this pull request is ready to get reviewed and merged.

2022-09-30 06:14 UTC, Yuyz0112 approved these changes

2022-09-30 06:14 UTC, merged